app.controller('mockDataController', [
  '$scope',
  function ($scope) {
    $scope.wines = [
      {
        name: 'Cakebread',
        vintage: 2018,
        color: 'red',
        price: 38.5,
        varietal: 'cabernet sauvignon',
        quantity: 12,
        region: 'ca',
      },
      {
        name: 'Silver Oak, Napa Valley',
        vintage: 2012,
        color: 'red',
        price: 145,
        varietal: 'Cabernet Sauvignon',
        quantity: 4,
        region: 'ca',
      },
      {
        name: 'Cakebread',
        vintage: 2018,
        color: 'red',
        price: 38.5,
        varietal: 'Other Red',
        quantity: 12,
        region: 'ca',
      },
      {
        name: 'Silver Oak',
        vintage: 2015,
        color: 'red',
        price: 155,
        varietal: 'cabernet sauvignon',
        quantity: 2,
        region: 'ca',
      },
      {
        name: 'Chateau Sauverain',
        vintage: 2018,
        color: 'white',
        price: 21,
        varietal: 'Chardonnay',
        quantity: 9,
        region: 'otherUs',
      },
      {
        name: 'Decoy',
        vintage: 2016,
        color: 'red',
        price: 82,
        varietal: 'merlot',
        quantity: 1,
        region: 'ca',
      },
    ];
  },
]);
